### ISSUE TITLE
Service worker caches backend

### ISSUE THREAD

**Issue by tgerulaitis** [meanbee/magento2-serviceworker#10]
Since the service worker is registered on the root of the Magento installation, all routes are affected unless they are explictly set to "NetworkOnly" strategy in the configuration. This means that if you visit the frontend first (which registers the service worker) and then navigate to the backend, the service worker stays active and uses the default strategy to serve requests.

While theoretically it would be interesting to speed up the admin area with service worker caching, currently it is a bit of a headache, especially if you start customising the caching strategies and using an app shell. For now, I think we should update the service worker JS to always use "NetworkOnly" strategy for any URL that matches the backend frontname.

**Comment by davidbrandastic** [comment]
One side-effect of this is the placement of the admin URI into a JS file that is accessible from the front end resulting in that data being potentially leaked to customers.

**Comment by tgerulaitis** [comment]
Good point, @davidbrandastic. Though I don't know if there's any way to get around that if we want to prevent the service worker from caching the backend.
