### ISSUE TITLE
2.2.2 and JS Minifcation

### ISSUE THREAD

**Issue by davidbrandastic** [meanbee/magento2-serviceworker#13]
- Enable JS Minification
- Deploy static content
- Receive the following warnings:
`#0 vendor\tedivm\jshrink\src\JShrink\Minifier.php(231): JShrink\Minifier->saveString()
#1 vendor\tedivm\jshrink\src\JShrink\Minifier.php(144): JShrink\Minifier->loop()
#2 vendor\tedivm\jshrink\src\JShrink\Minifier.php(110): JShrink\Minifier->minifyDirectToOutput('/*\n Copyright 2...', Array)
#3 vendor\magento\framework\Code\Minifier\Adapter\Js\JShrink.php(27): JShrink\Minifier::minify('/*\n Copyright 2...')
#4 vendor\magento\framework\View\Asset\PreProcessor\Minify.php(50): Magento\Framework\Code\Minifier\Adapter\Js\JShrink->minify('/*\n Copyright 2...')
#5 vendor\magento\framework\View\Asset\PreProcessor\Pool.php(77): Magento\Framework\View\Asset\PreProcessor\Minify->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#6 vendor\magento\framework\View\Asset\Source.php(152): Magento\Framework\View\Asset\PreProcessor\Pool->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#7 vendor\magento\framework\View\Asset\Source.php(105): Magento\Framework\View\Asset\Source->preProcess(Object(Magento\Framework\View\Asset\File))
#8 vendor\magento\framework\View\Asset\File.php(157): Magento\Framework\View\Asset\Source->getFile(Object(Magento\Framework\View\Asset\File))
#9 vendor\magento\framework\App\View\Asset\Publisher.php(73): Magento\Framework\View\Asset\File->getSourceFile()
#10 vendor\magento\framework\App\View\Asset\Publisher.php(61): Magento\Framework\App\View\Asset\Publisher->publishAsset(Object(Magento\Framework\View\Asset\File))
#11 vendor\magento\module-deploy\Service\DeployStaticFile.php(89): Magento\Framework\App\View\Asset\Publisher->publish(Object(Magento\Framework\View\Asset\File))
#12 vendor\magento\module-deploy\Service\DeployPackage.php(189): Magento\Deploy\Service\DeployStaticFile->deployFile('js/lib/workbox-...', Array)
#13 vendor\magento\module-deploy\Service\DeployPackage.php(136): Magento\Deploy\Service\DeployPackage->processFile(Object(Magento\Deploy\Package\PackageFile), Object(Magento\Deploy\Package\Package))
#14 vendor\magento\module-deploy\Service\DeployPackage.php(107): Magento\Deploy\Service\DeployPackage->deployEmulated(Object(Magento\Deploy\Package\Package), Array, false)
#15 [internal function]: Magento\Deploy\Service\DeployPackage->Magento\Deploy\Service\{closure}()
#16 vendor\magento\framework\App\State.php(186): call_user_func_array(Object(Closure), Array)
#17 vendor\magento\module-deploy\Service\DeployPackage.php(108): Magento\Framework\App\State->emulateAreaCode('frontend', Object(Closure))
#18 vendor\magento\module-deploy\Process\Queue.php(281): Magento\Deploy\Service\DeployPackage->deploy(Object(Magento\Deploy\Package\Package), Array)
#19 vendor\magento\module-deploy\Process\Queue.php(200): Magento\Deploy\Process\Queue->execute(Object(Magento\Deploy\Package\Package))
#20 vendor\magento\module-deploy\Process\Queue.php(162): Magento\Deploy\Process\Queue->assertAndExecute('frontend/Theme...', Array, Array)
#21 vendor\magento\module-deploy\Strategy\QuickDeploy.php(76): Magento\Deploy\Process\Queue->process()
#22 vendor\magento\module-deploy\Service\DeployStaticContent.php(109): Magento\Deploy\Strategy\QuickDeploy->deploy(Array)
#23 setup\src\Magento\Setup\Console\Command\DeployStaticContentCommand.php(140): Magento\Deploy\Service\DeployStaticContent->deploy(Array)
#24 vendor\symfony\console\Command\Command.php(242): Magento\Setup\Console\Command\DeployStaticContentCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 vendor\symfony\console\Application.php(842): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 vendor\symfony\console\Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DeployStaticContentCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))`
- 404 on JS files due to getViewFileUrl() returning a filename with .min that doesn't exist for workbox-sw.prod.v1.0.1.js
-- https://github.com/meanbee/magento2-serviceworker/blob/master/src/Block/Js.php#L73

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
