### ISSUE TITLE
Recomend supports sending Messages/Notifications

### ISSUE THREAD

**Issue by wubuyun** [meanbee/magento2-serviceworker#16]
[PHP API for Firebase Cloud Messaging from Google](https://github.com/redjanym/php-firebase-cloud-messaging)

 [Web Push library for PHP](https://github.com/web-push-libs/web-push-php)

[module-pwa magento2](https://github.com/Jakhotiya/module-pwa)

[module-pwa magento2](https://www.tigren.com/magento-2-extensions/progressive-web-apps-magento-2)

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
