### ISSUE TITLE
Not compatible with php7.2+

### ISSUE THREAD

**Issue by edward-simpson** [meanbee/magento2-serviceworker#19]
This module does not seem to be compatible with php7.2, or at very least it's composer.json states it is only compatible with 7/7.1

**Comment by edward-simpson** [comment]
Also is locked to specific magento/framework, magento/module-backend, magento/module-config, magento/module-cms versions

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
